name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v4
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9
    - name: Install Pearl
      run: |
        pip install -e .
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: facebookresearch/Pearl
